version: '3'

services:
    elasticsearch:
        image: docker.elastic.co/elasticsearch/elasticsearch:6.6.0
        ports:
            - "9200:9200"
            - "9300:9300"
        environment:
            - ES_JAVA_OPTS=-Xms512m -Xmx512m
        networks:
            - elastic

    kibana:
        image: docker.elastic.co/kibana/kibana:6.6.0
        ports:
            - "5601:5601"
        environment:
            - ES_JAVA_OPTS=-Xms512m -Xmx512m
        networks:
            - elastic

networks:
    elastic:
